### ISSUE TITLE
Order Included Relationships dont match

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-client-jsonapi#16]
I have been using a function with the Basket and Customer to match the "included" to their "data.relationships". Since each type and id are unique in the included , those become the index to finding the related data.
![Basket](https://user-images.githubusercontent.com/541161/134799324-d7ed9ff4-ad5c-45ab-a9e6-62184c959359.PNG)

Finally got around to the Order history and this function does not work because the mapping ID are different.
![Order](https://user-images.githubusercontent.com/541161/134799367-6099d1b2-fdef-4f25-a96d-6a52e3858533.PNG)

Since the id used in the Order Relationships section depend on attributes like ''order.base.product.id", it is nearly impossible to map these without an intimate knowledge of all the fields in the API.

Either the included order/base/product id should be the product id, Or the relationships id should be the position index.

**Comment by aimeos** [comment]
You are right, that's not how it should be.
The problem is fixed in dev-master and will be fixed in 2021.10 LTS but we don't dare to add that to 2021.07.x because it's somewhat breaking.

**Comment by exemplari** [comment]
thanks for the info. I found the needed relationship data exist in the attributes.
