### ISSUE TITLE
Customer handling (create new customer and authenticate user) using API

### ISSUE THREAD

**Issue by kumarJSS** [aimeos/ai-client-jsonapi#18]
Hi,

Can you please explain how to authenticate a user and create a new customer using the API? I need to implement login and new user registration using an API in my APPs.

     

1. I'm following the API documentation here: https://aimeos.org/docs/latest/frontend/jsonapi/customer/# create-new-customer

Where does the ajax call URL come from in JavaScript?

     

var url = result['links']['customer']['href']; // derived from the OPTIONS response

     

In the OPTIONS response, links doesn't have "customer" with "href" and I tried "self", but it is not working. Also, in "data.links.self.href" I tried, but it doesn't have a post method and it not works.

     

2. How do I use an API to authenticate a user?

**Comment by aimeos** [comment]
The customer resource link is in `result.meta.resource`:
https://aimeos.org/docs/latest/frontend/jsonapi/#retrieve-meta-data

Authentication is outside the scope of the Aimeos JSON API and you have to use Laravel Passport or Laravel Sanctum for authentication.

**Comment by kumarJSS** [comment]
> The customer resource link is in `result.meta.resource`: https://aimeos.org/docs/latest/frontend/jsonapi/#retrieve-meta-data
> 
> Authentication is outside the scope of the Aimeos JSON API and you have to use Laravel Passport or Laravel Sanctum for authentication.

Thanks a lot
