### ISSUE TITLE
[Docs] Return specific fields only - missing resource key

### ISSUE THREAD

**Issue by ProteanCode** [aimeos/ai-client-jsonapi#5]
https://aimeos.org/docs/Developers/Client/JSONAPI/Fetch_items#Return_specific_fields_only

The example for fetching the specific fields is incorrect
Its not:
`var params = {
    fields: 'product.id,product.label'
};`
but:
`"fields": {
		"product": "product.id,product.label"
	}`

**Comment by aimeos** [comment]
Thank you very much for you hint!
The documentation has been fixed now
