### ISSUE TITLE
ssl/https Retrieve meta data

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-client-jsonapi#9]
https://website.com/jsonapi/ -OPTIONS

{
"meta": {
"prefix": null,
"content-baseurl": "http://website.com"
....
, "csrf": {
}
}

EXPECTED 
"content-baseurl": "https://website.com"
+s

easily patched in the frontend, but unexpected

**Comment by aimeos** [comment]
If you are using Laravel, check your APP_URL setting in the .env file of your application and add https:// instead of http://

**Comment by exemplari** [comment]
Thanks. Thats it.
I setup with multi-site config for no particular reason. So the issue is actually that it is returning the laravel APP_URL which is totally different from my site url. 

APP_URL = http://manager.com

https://website.com/jsonapi/ -OPTIONS 
"content-baseurl" = "http://manager.com"

Not sure of that is an issue.

**Comment by aimeos** [comment]
It's a behaviour of the Laravel URL generator
